[package]
name = "rust_bluetooth_classic_scanwedge"
version = "0.1.0"
edition = "2024"

[dependencies]
io_bluetooth = "0.1.0"
winapi = { version = "0.3.9", features = ["bluetoothapis", "winbase", "winnt", "errhandlingapi", "bthdef"] }
btleplug = { version = "0.11.8", features = ["serde"] }
